### ISSUE TITLE
No module named '_sqlite3'

### ISSUE THREAD

**Issue by yuis-ice** [dbcli/litecli#108]
litecli --help
Traceback (most recent call last):
  File "/home/yuis/.pyenv/versions/3.6.12/bin/litecli", line 7, in <module>
    from litecli.main import cli
  File "/home/yuis/.pyenv/versions/3.6.12/lib/python3.6/site-packages/litecli/main.py", line 13, in <module>    
    from sqlite3 import OperationalError
  File "/home/yuis/.pyenv/versions/3.6.12/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/yuis/.pyenv/versions/3.6.12/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by amjith** [comment]
This seems like an issue with the python installed on your system. We use the standard library sqlite3 module. If this is throwing an exception then python isn't installed correctly in the system. 

Try opening the python shell and try to import the sqlite3 module as follows: 

```
$ python
>>> import sqlite3
>>> exit()
```

Please report back if you see any issues with that import.
