### ISSUE TITLE
litecli crashing on startup

### ISSUE THREAD

**Issue by herjazz** [dbcli/litecli#131]
Using Arch linux
Arch has just recently updated python 3.10 so that may be at the root of the issue

On start up litecli immediately crashes. Traceback below:

Traceback (most recent call last):
  File "/home/.../.local/bin/litecli", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/.../.local/lib/python3.10/site-packages/litecli/main.py", line 916, in cli
    litecli.run_cli()
  File "/home/.../.local/lib/python3.10/site-packages/litecli/main.py", line 558, in run_cli
    reserve_space_for_menu=self.get_reserved_space(),
  File "/home/.../.local/lib/python3.10/site-packages/litecli/main.py", line 818, in get_reserved_space
    _, height = click.get_terminal_size()
AttributeError: module 'click' has no attribute 'get_terminal_size'

I'm using version 1.7.0 installed via pip. No update available on pip at the time of this message

**Comment by amjith** [comment]
There is a new release of click and that's breaking compatibility. I'll get a fix soon.

**Comment by herjazz** [comment]
> There is a new release of click and that's breaking compatibility. I'll get a fix soon.

Thanks for the quick reply!

**Comment by amjith** [comment]
Can you try upgrading to the latest version? This is the command to upgrade to the latest version.

```
pip install -U litecli
```

**Comment by ricardoseriani** [comment]
For me it's OK now, thanks.

**Comment by herjazz** [comment]
> Can you try upgrading to the latest version? This is the command to upgrade to the latest version.
> 
> ```
> pip install -U litecli
> ```

Fine here too  - cheers!
